apiVersion: v1
kind: Service
metadata:
  name: veranafoundation-website
  namespace: web
  labels:
    app.kubernetes.io/name: veranafoundation-website
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: veranafoundation-website
